export const activityIcons: Record<string, string> = {
  stars: "✨",
  binoculars: "🔭",
  hiking: "🥾",
  water: "🌊",
  mountain: "⛰️",
  building: "🏛️",
  car: "🚙",
  search: "🔍",
  moon: "🌙",
  cave: "🕳️",
  feather: "🪶",
  eye: "👀",
  paw: "🐾",
  waterfall: "💧",
  wine: "🍷",
  shop: "🛍️",
  zap: "⚡",
  palette: "🎨",
  book: "📖",
  cart: "🛒",
  pin: "📍",
};
